version: '3'
services:
  backend:
    build:
      context: ../backend       
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app  
    networks:
      - app-network

  frontend:
    build:
      context: .     
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - app-network  
networks:
  app-network:  
    driver: bridge
